version: '3'

services:
    # The Hadatac Solr Service
    solr:
        build:
            context: ./solr
            dockerfile: Dockerfile
        container_name: hadatac_solr
        restart: always
        environment:
            SOLR_JAVA_MEM: "-Xms1g -Xmx1g"
        # Mount a volume in the mycores directory to persist data that is ingested.
        volumes:
            - hadatac-solr:/opt/solr/server
#            - /path in host server/solr-home:/opt/solr/server/solr/mycores   # Uncomment this option to use external binding
        networks:
            hadatac:
                aliases:
                    - solr
        ports:
            - "8983:8983"

    # The Hadatac Blazegraph instance
    blazegraph:
        build:
            context: ./blazegraph
            dockerfile: Dockerfile
        container_name: hadatac_blazegraph
        networks:
            hadatac:
                aliases:
                    - blazegraph
        ports:
            - "8080:8080"
        restart: always
        environment:
            JAVA_XMS: 512m
            JAVA_XMX: 4g
        volumes:
            - hadatac-blazegraph:/var/lib/jetty
#            - /path in host server/blazegraph/bigdata.jnl:/var/lib/jetty/bigdata.jnl # Uncomment this option to use external binding

    # The primary hadatac web app
    hadatac:
        build: ./
        restart: always
        container_name: hadatac
        tty: true
        ports:
            - "9000:9000"
        networks:
            hadatac:
                aliases:
                    - hadatac
        environment:
            JAVA_XMS: 2g
            JAVA_XMX: 12g
        volumes:
            # Creates a volume to store the various csv files. This allows the data
            #   to be persisted when the container is removed or when Hadatac is rebuilt.
            # Example command: docker cp <filename> hadatac:/root/app/csvs/unprocessed_csv

            # Comment out this option to use external binding
            - hadatac-csvs:/root/app/csvs
#            - /Users/kandws01/Documents/merge3/local:/root/app/csvs  # Uncomment this option to use external binding
            # Creates a volume for the config files. This way configuration file changes
            #   are persisted when the container is removed or rebuilt.

            # Comment out this option to use external binding
            - hadatac-conf:/root/app/conf
#            - /path in host server/conf:/root/app/conf # Uncomment this option to use external binding
        links:
            - blazegraph
            - solr
        depends_on:
            - blazegraph
            - solr

volumes:
    hadatac-solr:
    hadatac-blazegraph:
    hadatac-csvs:
    hadatac-conf:

networks:
    hadatac:
