version: '3'

services:
    # The Hadatac Solr Service
    solr:
        build:
            context: ./solr
            dockerfile: Dockerfile
        container_name: hadatac_solr
        restart: always
        # Mount a volume in the mycores directory to persist data that is ingested.
        volumes:
            - hadatac-solr:/opt/solr/server
        networks:
            hadatac:
                aliases:
                    - solr
        ports:
            - "8983:8983"

    # The Hadatac Blazegraph instance
    blazegraph:
        build:
            context: ./blazegraph
            dockerfile: Dockerfile
        container_name: hadatac_blazegraph
        networks:
            hadatac:
                aliases:
                    - blazegraph
        ports:
            - "8080:8080"
        restart: always
        environment:
            JAVA_XMS: 512m
            JAVA_XMX: 4g
        volumes:
            - hadatac-blazegraph:/var/lib/jetty

    # The primary hadatac web app
    hadatac:
        build: ./
        restart: always
        container_name: hadatac
        tty: true
        ports:
            - "9000:9000"
        networks:
            hadatac:
                aliases:
                    - hadatac
        volumes:
            # Creates a volume to store the various csv files. This allows the data
            #   to be persisted when the container is removed or when Hadatac is rebuilt.
            # Example command: docker cp <filename> hadatac:/root/app/csvs/unprocessed_csv
            - hadatac-csvs:/root/app/csvs
            # Creates a volume for the config files. This way configuration file changes
            #   are persisted when the container is removed or rebuilt.
            - hadatac-conf:/root/app/conf
        links:
            - blazegraph
            - solr
        depends_on:
            - blazegraph
            - solr

volumes:
    hadatac-solr:
    hadatac-blazegraph:
    hadatac-csvs:
    hadatac-conf:

networks:
    hadatac:
